./transforms testscenes/scene1.test
./transforms testscenes/scene2.test
./transforms testscenes/scene3.test
./transforms testscenes/scene4-ambient.test
./transforms testscenes/scene4-diffuse.test
./transforms testscenes/scene4-emission.test
./transforms testscenes/scene4-specular.test
./transforms testscenes/scene5.test
./transforms testscenes/scene6.test
#./transforms testscenes/scene7.test
